spring:
  datasource:
    hikari:
      maximum-pool-size: 4
#    driver-class-name:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/testdb
    username: admin
    password: pass
  # 404 Error
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  error:
    include-stacktrace: never


