spring:
  batch:
    job:
      enabled: false
  #    jdbc:
#      initialize-schema: always
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    primary:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/postgres
      username: admin
      password: pass
    batch:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:postgresql://127.0.0.1:5432/testdb
      username: admin
      password: pass
  # 404 Error
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.dataSource: quartzDataSource
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081
  error:
    include-stacktrace: never

jwt:
  header: Authorization
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3fn56zxcfd22rdhhgiygjnvcawQ21
